In [2]:
import polars as pl
# Import requested libraries

In [3]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [4]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [24]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [25]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [31]:
df.filter(pl.col("Customer ID").is_null())

shape: (107_927, 8)
┌─────────┬───────────┬────────────────────────┬──────────┬─────────────────────┬───────┬─────────────┬────────────────┐
│ Invoice ┆ StockCode ┆ Description            ┆ Quantity ┆ InvoiceDate         ┆ Price ┆ Customer ID ┆ Country        │
│ ---     ┆ ---       ┆ ---                    ┆ ---      ┆ ---                 ┆ ---   ┆ ---         ┆ ---            │
│ i64     ┆ str       ┆ str                    ┆ i64      ┆ datetime[ms]        ┆ f64   ┆ i64         ┆ str            │
╞═════════╪═══════════╪════════════════════════╪══════════╪═════════════════════╪═══════╪═════════════╪════════════════╡
│ 489464  ┆ 21733     ┆ 85123a mixed           ┆ -96      ┆ 2009-12-01 10:52:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 489463  ┆ 71477     ┆ short                  ┆ -240     ┆ 2009-12-01 10:52:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 489467  ┆ 85123A    ┆ 21733 mixed            ┆ -192     ┆ 2009-12-01 10:53:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 489521  ┆ 21646     ┆ null                   ┆ -50      ┆ 2009-12-01 11:44:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 489525  ┆ 85226C    ┆ BLUE PULL BACK RACING  ┆ 1        ┆ 2009-12-01 11:49:00 ┆ 0.55  ┆ null        ┆ United Kingdom │
│         ┆           ┆ CAR                    ┆          ┆                     ┆       ┆             ┆                │
│ …       ┆ …         ┆ …                      ┆ …        ┆ …                   ┆ …     ┆ …           ┆ …              │
│ 538159  ┆ 21324     ┆ null                   ┆ -18      ┆ 2010-12-09 17:17:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 538158  ┆ 20892     ┆ null                   ┆ -32      ┆ 2010-12-09 17:17:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 538160  ┆ 20956     ┆ null                   ┆ 288      ┆ 2010-12-09 17:18:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 538161  ┆ 46000S    ┆ Dotcom sales           ┆ -100     ┆ 2010-12-09 17:25:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
│ 538162  ┆ 46000M    ┆ Dotcom sales           ┆ -100     ┆ 2010-12-09 17:25:00 ┆ 0.0   ┆ null        ┆ United Kingdom │
└─────────┴───────────┴────────────────────────┴──────────┴─────────────────────┴───────┴─────────────┴────────────────┘