In [1]:
import polars as pl
from datetime import datetime
from datetime import date
# Import requested libraries

In [2]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [3]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [4]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [5]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [6]:
df = df.rename({
     "Invoice" : "invoice",
    "StockCode" : "stock_code",
    "Description" : "description",
    "InvoiceDate" : "invoice_date_time",
    "Quantity" : "quantity",
    "Price" : "price",
    "Customer ID" : "customer_id",
    "Country" : "country",
}
)
# Rename columns

In [7]:
df = df.with_columns(pl.col("invoice_date_time").dt.date().alias("invoice_date"))
df = df.with_columns(pl.col("invoice_date_time").dt.time().alias("invoice_time"))

In [8]:
df.filter((pl.col("stock_code") == "22087") & (pl.col("invoice_date") == date(2009, 12, 1)))

shape: (2, 10)
┌─────────┬────────────┬─────────────────────┬──────────┬───┬─────────────┬───────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description         ┆ quantity ┆ … ┆ customer_id ┆ country   ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---                 ┆ ---      ┆   ┆ ---         ┆ ---       ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str                 ┆ i64      ┆   ┆ i64         ┆ str       ┆ date         ┆ time         │
╞═════════╪════════════╪═════════════════════╪══════════╪═══╪═════════════╪═══════════╪══════════════╪══════════════╡
│ null    ┆ 22087      ┆ PAPER BUNTING WHITE ┆ -12      ┆ … ┆ 16321       ┆ Australia ┆ 2009-12-01   ┆ 10:33:00     │
│         ┆            ┆ LACE                ┆          ┆   ┆             ┆           ┆              ┆              │
│ 489450  ┆ 22087      ┆ PAPER BUNTING WHITE ┆ 12       ┆ … ┆ 16321       ┆ Australia ┆ 2009-12-01   ┆ 10:36:00     │
│         ┆            ┆ LACE                ┆          ┆   ┆             ┆           ┆              ┆              │
└─────────┴────────────┴─────────────────────┴──────────┴───┴─────────────┴───────────┴──────────────┴──────────────┘