In [23]:
import polars as pl
from datetime import datetime
from datetime import date
from datetime import time
# Import requested libraries

In [45]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [46]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [47]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [48]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [49]:
df = df.rename({
     "Invoice" : "invoice",
    "StockCode" : "stock_code",
    "Description" : "description",
    "InvoiceDate" : "invoice_date_time",
    "Quantity" : "quantity",
    "Price" : "price",
    "Customer ID" : "customer_id",
    "Country" : "country",
}
)
# Rename columns

In [50]:
df = df.with_columns(pl.col("invoice_date_time").dt.date().alias("invoice_date"))
df = df.with_columns(pl.col("invoice_date_time").dt.time().alias("invoice_time"))
# Separate invoice date and time column into date and time columns

In [51]:
duplicate_rows = df.group_by(df.columns).len(name = "count of repeated records").filter(pl.col("count of repeated records") > 1).sort(by = "count of repeated records", descending = True)
duplicate_rows
# Identify exact duplicate rows and count their occurrences

shape: (6_418, 11)
┌─────────┬────────────┬──────────────────────┬──────────┬───┬────────────────┬──────────────┬──────────────┬──────────┐
│ invoice ┆ stock_code ┆ description          ┆ quantity ┆ … ┆ country        ┆ invoice_date ┆ invoice_time ┆ count of │
│ ---     ┆ ---        ┆ ---                  ┆ ---      ┆   ┆ ---            ┆ ---          ┆ ---          ┆ repeated │
│ i64     ┆ str        ┆ str                  ┆ i64      ┆   ┆ str            ┆ date         ┆ time         ┆ records  │
│         ┆            ┆                      ┆          ┆   ┆                ┆              ┆              ┆ ---      │
│         ┆            ┆                      ┆          ┆   ┆                ┆              ┆              ┆ u32      │
╞═════════╪════════════╪══════════════════════╪══════════╪═══╪════════════════╪══════════════╪══════════════╪══════════╡
│ 496431  ┆ 84826      ┆ ASSTD DESIGN 3D      ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-02-01   ┆ 12:30:00     ┆ 6        │
│         ┆            ┆ PAPER STICKERS       ┆          ┆   ┆                ┆              ┆              ┆          │
│ 502660  ┆ 17021      ┆ NAMASTE SWAGAT       ┆ 6        ┆ … ┆ United Kingdom ┆ 2010-03-25   ┆ 17:18:00     ┆ 6        │
│         ┆            ┆ INCENSE              ┆          ┆   ┆                ┆              ┆              ┆          │
│ 534219  ┆ 35953      ┆ FOLKART STAR         ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-11-21   ┆ 16:13:00     ┆ 6        │
│         ┆            ┆ CHRISTMAS DECORAT…   ┆          ┆   ┆                ┆              ┆              ┆          │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE       ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     ┆ 6        │
│         ┆            ┆ T-LIGHT HOLDER …     ┆          ┆   ┆                ┆              ┆              ┆          │
│ 520570  ┆ 21755      ┆ LOVE BUILDING BLOCK  ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-08-26   ┆ 20:07:00     ┆ 5        │
│         ┆            ┆ WORD                 ┆          ┆   ┆                ┆              ┆              ┆          │
│ …       ┆ …          ┆ …                    ┆ …        ┆ … ┆ …              ┆ …            ┆ …            ┆ …        │
│ 531350  ┆ 22652      ┆ TRAVEL SEWING KIT    ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-11-07   ┆ 13:31:00     ┆ 2        │
│ 518652  ┆ 84931A     ┆ PINK SCOTTIE DOG W   ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-08-10   ┆ 13:28:00     ┆ 2        │
│         ┆            ┆ FLOWER PATT…         ┆          ┆   ┆                ┆              ┆              ┆          │
│ 525698  ┆ 22629      ┆ SPACEBOY LUNCH BOX   ┆ 12       ┆ … ┆ Germany        ┆ 2010-10-06   ┆ 12:36:00     ┆ 2        │
│ 532297  ┆ 22843      ┆ BISCUIT TIN VINTAGE  ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-11-11   ┆ 13:50:00     ┆ 2        │
│         ┆            ┆ GREEN                ┆          ┆   ┆                ┆              ┆              ┆          │
│ 535571  ┆ 47422      ┆ ASSORTED MONKEY      ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-11-26   ┆ 15:36:00     ┆ 2        │
│         ┆            ┆ SUCTION CUP HO…      ┆          ┆   ┆                ┆              ┆              ┆          │
└─────────┴────────────┴──────────────────────┴──────────┴───┴────────────────┴──────────────┴──────────────┴──────────┘

In [52]:
df.filter((pl.col("customer_id") == 16799) & (pl.col("invoice_time") == time(14,28,0)) & (pl.col("stock_code") == "20894"))
# Verify whether identified duplicate records are exact matches

shape: (6, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [53]:
duplicate_percentage = (df.is_duplicated().sum()/df.shape[0]) * 100 
print(f"Duplicate rows : {df.is_duplicated().sum()}")
print(f"Percentage of duplicate rows : {duplicate_percentage:.2f} %")
# Calculate duplicate rows and percentage of duplicate records

Duplicate rows : 13283
Percentage of duplicate rows : 2.53 %

In [55]:
df = df.unique()
# Remove exact duplicate rows from the DataFrame

In [37]:
df = df.drop_nulls(subset = "customer_id")
df

shape: (410_763, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 525082  ┆ 16012      ┆ FOOD/DRINK SPONGE ┆ 24       ┆ … ┆ 14455       ┆ United Kingdom ┆ 2010-10-03   ┆ 15:48:00     │
│         ┆            ┆ STICKERS          ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22650      ┆ CERAMIC PIRATE    ┆ -12      ┆ … ┆ 15639       ┆ United Kingdom ┆ 2010-09-16   ┆ 12:37:00     │
│         ┆            ┆ CHEST MONEY BAN…  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 503427  ┆ 21792      ┆ CLASSIC FRENCH    ┆ 1        ┆ … ┆ 13576       ┆ United Kingdom ┆ 2010-03-31   ┆ 17:29:00     │
│         ┆            ┆ STYLE BASKET GR…  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525872  ┆ 22175      ┆ PINK OWL SOFT TOY ┆ 6        ┆ … ┆ 12393       ┆ Australia      ┆ 2010-10-07   ┆ 13:49:00     │
│ 534181  ┆ 21875      ┆ KINGS CHOICE MUG  ┆ 12       ┆ … ┆ 17244       ┆ United Kingdom ┆ 2010-11-21   ┆ 13:53:00     │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ 498903  ┆ 21833      ┆ CAMOUFLAGE LED    ┆ 12       ┆ … ┆ 14112       ┆ United Kingdom ┆ 2010-02-23   ┆ 14:16:00     │
│         ┆            ┆ TORCH             ┆          ┆   ┆             ┆                ┆              ┆              │
│ 515179  ┆ 20733      ┆ GOLD MINI TAPE    ┆ 20       ┆ … ┆ 16032       ┆ United Kingdom ┆ 2010-07-08   ┆ 18:33:00     │
│         ┆            ┆ MEASURE           ┆          ┆   ┆             ┆                ┆              ┆              │
│ 495077  ┆ 22217      ┆ T-LIGHT HOLDER    ┆ 12       ┆ … ┆ 16634       ┆ United Kingdom ┆ 2010-01-21   ┆ 09:30:00     │
│         ┆            ┆ HANGING LACE      ┆          ┆   ┆             ┆                ┆              ┆              │
│ 517323  ┆ 37503      ┆ TEA TIME CAKE     ┆ 1        ┆ … ┆ 15768       ┆ United Kingdom ┆ 2010-07-28   ┆ 12:18:00     │
│         ┆            ┆ STAND IN GIFT BO… ┆          ┆   ┆             ┆                ┆              ┆              │
│ 491654  ┆ 21431      ┆ GREEN GINGHAM     ┆ 4        ┆ … ┆ 16104       ┆ United Kingdom ┆ 2009-12-13   ┆ 10:54:00     │
│         ┆            ┆ FLOWER JEWELLERY… ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [43]:
df.filter(pl.col("invoice").is_null()).sort(by = "customer_id", descending = False)

shape: (9_816, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ null    ┆ M          ┆ Manual            ┆ -1       ┆ … ┆ 12346       ┆ United Kingdom ┆ 2010-06-30   ┆ 11:22:00     │
│ null    ┆ M          ┆ Manual            ┆ -1       ┆ … ┆ 12346       ┆ United Kingdom ┆ 2010-06-30   ┆ 11:22:00     │
│ null    ┆ M          ┆ Manual            ┆ -1       ┆ … ┆ 12346       ┆ United Kingdom ┆ 2010-06-30   ┆ 11:22:00     │
│ null    ┆ TEST001    ┆ This is a test    ┆ -1       ┆ … ┆ 12346       ┆ United Kingdom ┆ 2010-10-04   ┆ 16:33:00     │
│         ┆            ┆ product.          ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ ADJUST     ┆ Adjustment by     ┆ -1       ┆ … ┆ 12346       ┆ United Kingdom ┆ 2010-01-26   ┆ 17:27:00     │
│         ┆            ┆ john on 26/01/20… ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ null    ┆ C2         ┆ CARRIAGE          ┆ -1       ┆ … ┆ 18284       ┆ United Kingdom ┆ 2010-10-06   ┆ 12:31:00     │
│ null    ┆ 79323G     ┆ GOLD  CHERRY      ┆ -4       ┆ … ┆ 18286       ┆ United Kingdom ┆ 2010-06-24   ┆ 17:51:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 79323S     ┆ SILVER CHERRY     ┆ -4       ┆ … ┆ 18286       ┆ United Kingdom ┆ 2010-06-24   ┆ 17:51:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 79323B     ┆ BLACK CHERRY      ┆ -8       ┆ … ┆ 18286       ┆ United Kingdom ┆ 2010-06-24   ┆ 17:51:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22301      ┆ COFFEE MUG CAT +  ┆ -2       ┆ … ┆ 18287       ┆ United Kingdom ┆ 2009-12-01   ┆ 14:19:00     │
│         ┆            ┆ BIRD DESIGN       ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [59]:
df_negative_quantity = df.filter(pl.col("quantity") < 0 )