In [2]:
import polars as pl
# Import requested libraries

In [3]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [4]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [5]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [13]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [18]:
df.filter(pl.col("StockCode") == "22087")

shape: (564, 8)
┌─────────┬───────────┬─────────────────────┬──────────┬─────────────────────┬───────┬─────────────┬────────────────┐
│ Invoice ┆ StockCode ┆ Description         ┆ Quantity ┆ InvoiceDate         ┆ Price ┆ Customer ID ┆ Country        │
│ ---     ┆ ---       ┆ ---                 ┆ ---      ┆ ---                 ┆ ---   ┆ ---         ┆ ---            │
│ i64     ┆ str       ┆ str                 ┆ i64      ┆ datetime[ms]        ┆ f64   ┆ i64         ┆ str            │
╞═════════╪═══════════╪═════════════════════╪══════════╪═════════════════════╪═══════╪═════════════╪════════════════╡
│ null    ┆ 22087     ┆ PAPER BUNTING WHITE ┆ -12      ┆ 2009-12-01 10:33:00 ┆ 2.95  ┆ 16321       ┆ Australia      │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 489450  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 12       ┆ 2009-12-01 10:36:00 ┆ 2.95  ┆ 16321       ┆ Australia      │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 489857  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 2        ┆ 2009-12-02 14:43:00 ┆ 6.04  ┆ null        ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 489866  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 1        ┆ 2009-12-02 15:04:00 ┆ 2.95  ┆ 16200       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 489894  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 12       ┆ 2009-12-02 17:18:00 ┆ 2.95  ┆ 17716       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ …       ┆ …         ┆ …                   ┆ …        ┆ …                   ┆ …     ┆ …           ┆ …              │
│ 537224  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 2        ┆ 2010-12-05 16:24:00 ┆ 2.95  ┆ 13174       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 537405  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 1        ┆ 2010-12-06 14:51:00 ┆ 2.95  ┆ 17841       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 537592  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 12       ┆ 2010-12-07 12:18:00 ┆ 2.95  ┆ 17491       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 537646  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 1        ┆ 2010-12-07 15:39:00 ┆ 2.95  ┆ 17591       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
│ 537889  ┆ 22087     ┆ PAPER BUNTING WHITE ┆ 6        ┆ 2010-12-09 10:04:00 ┆ 2.95  ┆ 13319       ┆ United Kingdom │
│         ┆           ┆ LACE                ┆          ┆                     ┆       ┆             ┆                │
└─────────┴───────────┴─────────────────────┴──────────┴─────────────────────┴───────┴─────────────┴────────────────┘

In [21]:
df["invoice_date"] = df.with_columns(pl.col("InvoiceDate").str.split(" "))

SchemaError: invalid series dtype: expected `String`, got `datetime[ms]` for series with name `InvoiceDate`

This error occurred in the following expression:
	col("InvoiceDate").str.split([" "])