In [1]:
import polars as pl
from datetime import datetime
from datetime import date
from datetime import time
# Import requested libraries

In [2]:
df = pl.read_excel(r"C:\Users\LENOVO\Desktop\Data Analitika\Customer-Segmentation-and-Recommendation-System\data\raw\online_retail_.xlsx")
# Read excel file

In [3]:
df.glimpse()
# Check for general info about the dataset

Rows: 525461
Columns: 8
$ Invoice              <i64> 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489434, 489435, 489435
$ StockCode            <str> '85048', '79323P', '79323W', '22041', '21232', '22064', '21871', '21523', '22350', '22349'
$ Description          <str> '15CM CHRISTMAS GLASS BALL 20 LIGHTS', 'PINK CHERRY LIGHTS', ' WHITE CHERRY LIGHTS', 'RECORD FRAME 7" SINGLE SIZE ', 'STRAWBERRY CERAMIC TRINKET BOX', 'PINK DOUGHNUT TRINKET POT ', 'SAVE THE PLANET MUG', 'FANCY FONT HOME SWEET HOME DOORMAT', 'CAT BOWL ', 'DOG BOWL , CHASING BALL DESIGN'
$ Quantity             <i64> 12, 12, 12, 48, 24, 24, 24, 10, 12, 12
$ InvoiceDate <datetime[ms]> 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:45:00, 2009-12-01 07:46:00, 2009-12-01 07:46:00
$ Price                <f64> 6.95, 6.75, 6.75, 2.1, 1.25, 1.65, 1.25, 5.95, 2.55, 3.75
$ Customer ID          <i64> 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085, 13085
$ Country              <str> 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom', 'United Kingdom'

In [4]:
df.is_duplicated().sum()
# Count of duplicate records

13283

In [5]:
df.null_count().sum()
# Check for null values

shape: (1, 8)
┌─────────┬───────────┬─────────────┬──────────┬─────────────┬───────┬─────────────┬─────────┐
│ Invoice ┆ StockCode ┆ Description ┆ Quantity ┆ InvoiceDate ┆ Price ┆ Customer ID ┆ Country │
│ ---     ┆ ---       ┆ ---         ┆ ---      ┆ ---         ┆ ---   ┆ ---         ┆ ---     │
│ u32     ┆ u32       ┆ u32         ┆ u32      ┆ u32         ┆ u32   ┆ u32         ┆ u32     │
╞═════════╪═══════════╪═════════════╪══════════╪═════════════╪═══════╪═════════════╪═════════╡
│ 10209   ┆ 0         ┆ 2928        ┆ 0        ┆ 0           ┆ 0     ┆ 107927      ┆ 0       │
└─────────┴───────────┴─────────────┴──────────┴─────────────┴───────┴─────────────┴─────────┘

In [6]:
df = df.rename({
     "Invoice" : "invoice",
    "StockCode" : "stock_code",
    "Description" : "description",
    "InvoiceDate" : "invoice_date_time",
    "Quantity" : "quantity",
    "Price" : "price",
    "Customer ID" : "customer_id",
    "Country" : "country",
}
)
# Rename columns

In [7]:
df = df.with_columns(pl.col("invoice_date_time").dt.date().alias("invoice_date"))
df = df.with_columns(pl.col("invoice_date_time").dt.time().alias("invoice_time"))
# Separate invoice date and time column into date and time columns

In [8]:
duplicate_rows = df.group_by(df.columns).len(name = "count of repeated records").filter(pl.col("count of repeated records") > 1).sort(by = "count of repeated records", descending = True)
duplicate_rows
# Identify exact duplicate rows and count their occurrences

shape: (6_418, 11)
┌─────────┬────────────┬──────────────────────┬──────────┬───┬────────────────┬──────────────┬──────────────┬──────────┐
│ invoice ┆ stock_code ┆ description          ┆ quantity ┆ … ┆ country        ┆ invoice_date ┆ invoice_time ┆ count of │
│ ---     ┆ ---        ┆ ---                  ┆ ---      ┆   ┆ ---            ┆ ---          ┆ ---          ┆ repeated │
│ i64     ┆ str        ┆ str                  ┆ i64      ┆   ┆ str            ┆ date         ┆ time         ┆ records  │
│         ┆            ┆                      ┆          ┆   ┆                ┆              ┆              ┆ ---      │
│         ┆            ┆                      ┆          ┆   ┆                ┆              ┆              ┆ u32      │
╞═════════╪════════════╪══════════════════════╪══════════╪═══╪════════════════╪══════════════╪══════════════╪══════════╡
│ 502660  ┆ 17021      ┆ NAMASTE SWAGAT       ┆ 6        ┆ … ┆ United Kingdom ┆ 2010-03-25   ┆ 17:18:00     ┆ 6        │
│         ┆            ┆ INCENSE              ┆          ┆   ┆                ┆              ┆              ┆          │
│ 496431  ┆ 84826      ┆ ASSTD DESIGN 3D      ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-02-01   ┆ 12:30:00     ┆ 6        │
│         ┆            ┆ PAPER STICKERS       ┆          ┆   ┆                ┆              ┆              ┆          │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE       ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     ┆ 6        │
│         ┆            ┆ T-LIGHT HOLDER …     ┆          ┆   ┆                ┆              ┆              ┆          │
│ 534219  ┆ 35953      ┆ FOLKART STAR         ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-11-21   ┆ 16:13:00     ┆ 6        │
│         ┆            ┆ CHRISTMAS DECORAT…   ┆          ┆   ┆                ┆              ┆              ┆          │
│ 530953  ┆ 21231      ┆ SWEETHEART CERAMIC   ┆ 4        ┆ … ┆ United Kingdom ┆ 2010-11-04   ┆ 18:42:00     ┆ 5        │
│         ┆            ┆ TRINKET BOX          ┆          ┆   ┆                ┆              ┆              ┆          │
│ …       ┆ …          ┆ …                    ┆ …        ┆ … ┆ …              ┆ …            ┆ …            ┆ …        │
│ 533592  ┆ 22082      ┆ RIBBON REEL STRIPES  ┆ 5        ┆ … ┆ United Kingdom ┆ 2010-11-18   ┆ 12:08:00     ┆ 2        │
│         ┆            ┆ DESIGN               ┆          ┆   ┆                ┆              ┆              ┆          │
│ 512772  ┆ 22171      ┆ 3 HOOK PHOTO SHELF   ┆ 2        ┆ … ┆ United Kingdom ┆ 2010-06-17   ┆ 17:00:00     ┆ 2        │
│         ┆            ┆ ANTIQUE WHI…         ┆          ┆   ┆                ┆              ┆              ┆          │
│ 519192  ┆ 22297      ┆ HEART IVORY TRELLIS  ┆ 24       ┆ … ┆ United Kingdom ┆ 2010-08-13   ┆ 16:58:00     ┆ 2        │
│         ┆            ┆ SMALL                ┆          ┆   ┆                ┆              ┆              ┆          │
│ 508652  ┆ 85185B     ┆ PINK HORSE SOCK      ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-05-17   ┆ 15:48:00     ┆ 2        │
│         ┆            ┆ PUPPET               ┆          ┆   ┆                ┆              ┆              ┆          │
│ 494359  ┆ 84050      ┆ PINK HEART SHAPE EGG ┆ 1        ┆ … ┆ United Kingdom ┆ 2010-01-13   ┆ 15:24:00     ┆ 2        │
│         ┆            ┆ FRYING PA…           ┆          ┆   ┆                ┆              ┆              ┆          │
└─────────┴────────────┴──────────────────────┴──────────┴───┴────────────────┴──────────────┴──────────────┴──────────┘

In [9]:
df.filter((pl.col("customer_id") == 16799) & (pl.col("invoice_time") == time(14,28,0)) & (pl.col("stock_code") == "20894"))
# Verify whether identified duplicate records are exact matches

shape: (6, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
│ 525065  ┆ 20894      ┆ HANGING BAUBLE    ┆ 1        ┆ … ┆ 16799       ┆ United Kingdom ┆ 2010-10-03   ┆ 14:28:00     │
│         ┆            ┆ T-LIGHT HOLDER …  ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘

In [10]:
duplicate_percentage = (df.is_duplicated().sum()/df.shape[0]) * 100 
print(f"Duplicate rows : {df.is_duplicated().sum()}")
print(f"Percentage of duplicate rows : {duplicate_percentage:.2f} %")
# Calculate duplicate rows and percentage of duplicate records

Duplicate rows : 13283
Percentage of duplicate rows : 2.53 %

In [11]:
df = df.unique()
# Remove exact duplicate rows from the DataFrame

In [12]:
df = df.drop_nulls(subset = "customer_id")
# Remove rows with missing customer IDs

In [14]:
df_negative_qunatity = df.filter(pl.col("quantity") < 0)
df_negative_qunatity
# Separate records with missing invoice numbers and negative quantities for further investigation

shape: (9_816, 10)
┌─────────┬────────────┬───────────────────┬──────────┬───┬─────────────┬────────────────┬──────────────┬──────────────┐
│ invoice ┆ stock_code ┆ description       ┆ quantity ┆ … ┆ customer_id ┆ country        ┆ invoice_date ┆ invoice_time │
│ ---     ┆ ---        ┆ ---               ┆ ---      ┆   ┆ ---         ┆ ---            ┆ ---          ┆ ---          │
│ i64     ┆ str        ┆ str               ┆ i64      ┆   ┆ i64         ┆ str            ┆ date         ┆ time         │
╞═════════╪════════════╪═══════════════════╪══════════╪═══╪═════════════╪════════════════╪══════════════╪══════════════╡
│ null    ┆ 84077      ┆ WORLD WAR 2       ┆ -48      ┆ … ┆ 13585       ┆ United Kingdom ┆ 2010-05-17   ┆ 14:34:00     │
│         ┆            ┆ GLIDERS ASSTD     ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ DESI…             ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 79323GR    ┆ GREEN CHERRY      ┆ -24      ┆ … ┆ 15125       ┆ United Kingdom ┆ 2010-05-18   ┆ 09:29:00     │
│         ┆            ┆ LIGHTS            ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22766      ┆ PHOTO FRAME       ┆ -4       ┆ … ┆ 15885       ┆ United Kingdom ┆ 2010-10-21   ┆ 13:41:00     │
│         ┆            ┆ CORNICE           ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22167      ┆ WALL MIRROR ,     ┆ -1       ┆ … ┆ 15005       ┆ United Kingdom ┆ 2010-01-18   ┆ 14:58:00     │
│         ┆            ┆ DIAMANTE OVAL SH… ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 22890      ┆ NOVELTY BISCUITS  ┆ -2       ┆ … ┆ 14870       ┆ United Kingdom ┆ 2010-11-04   ┆ 11:13:00     │
│         ┆            ┆ CAKE STAND 3 …    ┆          ┆   ┆             ┆                ┆              ┆              │
│ …       ┆ …          ┆ …                 ┆ …        ┆ … ┆ …           ┆ …              ┆ …            ┆ …            │
│ null    ┆ 21664      ┆ RIDGED GLASS      ┆ -1       ┆ … ┆ 17961       ┆ United Kingdom ┆ 2010-06-30   ┆ 08:16:00     │
│         ┆            ┆ STORAGE JAR       ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ CREAM…            ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 21035      ┆ SET/2 RED         ┆ -5       ┆ … ┆ 12986       ┆ United Kingdom ┆ 2010-10-22   ┆ 11:23:00     │
│         ┆            ┆ RETROSPOT TEA     ┆          ┆   ┆             ┆                ┆              ┆              │
│         ┆            ┆ TOWELS…           ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 85059      ┆ FRENCH ENAMEL     ┆ -1       ┆ … ┆ 12531       ┆ Germany        ┆ 2010-01-28   ┆ 10:43:00     │
│         ┆            ┆ WATER BASIN       ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 35400      ┆ WOODEN BOX ADVENT ┆ -2       ┆ … ┆ 17476       ┆ United Kingdom ┆ 2009-12-17   ┆ 17:51:00     │
│         ┆            ┆ CALENDAR          ┆          ┆   ┆             ┆                ┆              ┆              │
│ null    ┆ 21927      ┆ BLUE/CREAM STRIPE ┆ -12      ┆ … ┆ 12779       ┆ Poland         ┆ 2010-11-18   ┆ 10:23:00     │
│         ┆            ┆ CUSHION COVE…     ┆          ┆   ┆             ┆                ┆              ┆              │
└─────────┴────────────┴───────────────────┴──────────┴───┴─────────────┴────────────────┴──────────────┴──────────────┘